// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaitingList.Database;

#nullable disable

namespace WaitingList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WaitingList.Models.PartyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsReady")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsServiceEnded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<Guid>("WaitingListModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WaitingListModelId");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("WaitingList.Models.WaitingListModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TimeForService")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeatsAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WaitingLists");
                });

            modelBuilder.Entity("WaitingList.Models.PartyModel", b =>
                {
                    b.HasOne("WaitingList.Models.WaitingListModel", "WaitingListModel")
                        .WithMany("Parties")
                        .HasForeignKey("WaitingListModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WaitingListModel");
                });

            modelBuilder.Entity("WaitingList.Models.WaitingListModel", b =>
                {
                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
